# Generated by Django 4.1.1 on 2022-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_rating_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Логотип'),
        ),
    ]
