# Generated by Django 4.1.1 on 2022-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stocks_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='dividend',
            field=models.FloatField(default=0, verbose_name='Дивиденды'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='proffit_52',
            field=models.FloatField(default=0, help_text='Указывать в процентах', verbose_name='Профит за 52 недели'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='weight_to_index',
            field=models.FloatField(default=0, help_text='Указывать в процентах', verbose_name='Вес в индексе'),
        ),
    ]
