# Generated by Django 4.1.1 on 2022-09-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stocks_dividend_alter_stocks_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='proffit_52',
            field=models.TextField(default=0, help_text='Указывать в процентах', verbose_name='Профит за 52 недели'),
        ),
    ]
