# Generated by Django 4.1.1 on 2022-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stocks_proffit_52'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='dividend',
            field=models.FloatField(default=0, null=True, verbose_name='Дивиденды'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Акция'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='proffit_52',
            field=models.TextField(default=0, help_text='Указывать в процентах', null=True, verbose_name='Профит за 52 недели'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='tiker',
            field=models.CharField(max_length=10, null=True, verbose_name='Тикер'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='weight_to_index',
            field=models.FloatField(default=0, help_text='Указывать в процентах', null=True, verbose_name='Вес в индексе'),
        ),
    ]
